agents:
  visibility: "public"
  os: "linux"

steps:
  - command: nix flake archive .#
    label: ":nixos: Archive Nix flake inputs"

  - command: nix-buildkite
    label: ":nixos: :buildkite:"
    plugins:
      - hackworthltd/nix#v1.0.0:
          file: nix/ci.nix

