agents:
  public: "true"
  os: "linux"

steps:
  - command: nix-buildkite
    label: ":nixos: :buildkite:"
    plugins:
      - circuithub/nix-buildkite:
          file: nix/ci.nix
          post-build-hook:
            /run/current-system/sw/bin/buildkite-public-post-build-hook
  - command: nix flake archive --json | jq -r '.path,(.inputs|to_entries[].value.path)' | cachix --verbose --config /var/lib/cachix/hackworthltd/cachix.dhall push hackworthltd
    label: ":nixos: Archive Nix flake inputs"
