agents:
  public: "true"
  os: "linux"

steps:
  - command: nix-buildkite
    label: ":nixos: :buildkite:"
    plugins:
      - circuithub/nix-buildkite:
          file: nix/ci.nix

  - command: nix flake archive .#
    label: ":nixos: Archive Nix flake inputs"
