agents:
  public: "true"

steps:
  - command: nix-buildkite
    label: ":nixos: :buildkite:"
    plugins:
      - hackworthltd/nix-buildkite#hackworthltd-v4:
          file: nix/ci.nix
          post-build-hook:
            buildkite-public-post-build-hook
