steps:
  - command: nix-buildkite
    label: ":nixos: :buildkite:"
    plugins:
      circuithub/nix-buildkite:
        file: nix/buildkite.nix
  - command: buildkite-agent pipeline upload
    label: ":pipeline:"
