agents:
  queue: "nix-eval"

steps:
  - command: nix flake archive .#
    label: ":nixos: Archive Nix flake inputs"
    agents:
      queue: "nix-build"

  - command: nix-buildkite
    label: ":nixos: :buildkite:"
    plugins:
      - hackworthltd/nix#v1.0.0:
          file: nix/ci.nix
          agent-tags: queue=nix-build,os=linux
