agents:
  public: "true"

steps:
  - command: nix-buildkite
    label: ":nixos: :buildkite:"
    plugins:
      - hackworthltd/nix-buildkite#hackworthltd-v5:
          file: nix/ci.nix
          post-build-hook:
            /run/current-system/sw/bin/buildkite-public-post-build-hook
