agents:
  public: "true"

env:
  CACHIX_NAME: hackworthltd

steps:
  - command: nix-buildkite
    label: ":nixos: :buildkite:"
    plugins:
      - hackworthltd/nix-buildkite#a0dde6ac1a66ed56744ab4c737f0ce2cc409da60:
          file: nix/ci.nix

