name: Update Nix dependencies.

on:
    workflow_dispatch:
    schedule:
        # 11 pm every Friday
        - cron: "0 23 * * 5"

jobs:
    update-nix-dependencies:
        permissions:
            contents: read
            pull-requests: write

        uses: hackworthltd/.github/.github/workflows/reusable-update-nix-flake-public.yml@main
